# Terraform Provider release workflow.
name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  goreleaser:
    uses: turbot/steampipe-workflows/.github/workflows/terraform-release.yml@main
    secrets: inherit
